name: "yoloface_8n"
platform: "onnxruntime_onnx"
max_batch_size: 255

input [
	{
		name: input,
		data_type: TYPE_FP32,
		dims: [3, 640, 640]
	},
]

output [
	{
		name: output,
		data_type: TYPE_FP32,
		dims: [20, 8400]
	},
]
